//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Input/conversation.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Conversation : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Conversation()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""conversation"",
    ""maps"": [
        {
            ""name"": ""talk"",
            ""id"": ""23915d87-0397-402e-91ca-78cbf7627a94"",
            ""actions"": [
                {
                    ""name"": ""continue"",
                    ""type"": ""Button"",
                    ""id"": ""0430fe17-9fb4-4ef2-86fb-7c809f4777b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c81c4733-bd80-494b-a31b-a9d309e1e3ff"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press(pressPoint=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // talk
        m_talk = asset.FindActionMap("talk", throwIfNotFound: true);
        m_talk_continue = m_talk.FindAction("continue", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // talk
    private readonly InputActionMap m_talk;
    private ITalkActions m_TalkActionsCallbackInterface;
    private readonly InputAction m_talk_continue;
    public struct TalkActions
    {
        private @Conversation m_Wrapper;
        public TalkActions(@Conversation wrapper) { m_Wrapper = wrapper; }
        public InputAction @continue => m_Wrapper.m_talk_continue;
        public InputActionMap Get() { return m_Wrapper.m_talk; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TalkActions set) { return set.Get(); }
        public void SetCallbacks(ITalkActions instance)
        {
            if (m_Wrapper.m_TalkActionsCallbackInterface != null)
            {
                @continue.started -= m_Wrapper.m_TalkActionsCallbackInterface.OnContinue;
                @continue.performed -= m_Wrapper.m_TalkActionsCallbackInterface.OnContinue;
                @continue.canceled -= m_Wrapper.m_TalkActionsCallbackInterface.OnContinue;
            }
            m_Wrapper.m_TalkActionsCallbackInterface = instance;
            if (instance != null)
            {
                @continue.started += instance.OnContinue;
                @continue.performed += instance.OnContinue;
                @continue.canceled += instance.OnContinue;
            }
        }
    }
    public TalkActions @talk => new TalkActions(this);
    public interface ITalkActions
    {
        void OnContinue(InputAction.CallbackContext context);
    }
}
